apiVersion: v1
kind: Service
metadata:
  name: order-backend-service
  labels:
    app: order-backend
spec:
  selector:
    app: order-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
